service:
  ip: 0.0.0.0
  port: 17271
  log_level: DEBUG
  timeout_second: 60
doris:
  endpoint: doris:9030
  username: admin
  password:
  database: otel
  table_name: otel_traces
  timezone: Asia/Shanghai
