{
 "title": "Metrics",
 "time": { "from": "2024-09-24T07:05:41.626Z", "to": "2024-09-24T09:25:17.870Z" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "service_name",
    "query": "select service_name from otel_metrics_gauge group by service_name\nunion\nselect service_name from otel_metrics_sum group by service_name\nunion\nselect service_name from otel_metrics_histogram group by service_name"
   },
   {
    "name": "metric_gauge",
    "label": "metric_gauge",
    "query": "select metric_name from otel_metrics_gauge where service_name = '$service_name' group by metric_name;"
   },
   {
    "name": "metric_gauge_attributes",
    "label": "metric_gauge_attributes",
    "query": "select cast(attributes as text) as attr from otel_metrics_gauge where service_name = '$service_name' and metric_name = '$metric_gauge' group by attr;"
   },
   {
    "name": "metric_sum",
    "label": "metric_sum",
    "query": "select metric_name from otel_metrics_sum where service_name='$service_name' group by metric_name;"
   },
   {
    "name": "metric_sum_attributes",
    "label": "metric_sum_attributes",
    "query": "select cast(attributes as text) as attr from otel_metrics_sum where service_name = '$service_name' and metric_name = '$metric_sum' group by attr;"
   },
   {
    "name": "metric_histogram",
    "label": "metric_histogram",
    "query": "select metric_name from otel_metrics_histogram where service_name = '$service_name' group by metric_name;"
   },
   {
    "name": "metric_histogram_attributes",
    "label": "metric_histogram_attributes",
    "query": "select cast(attributes as text) as attr from otel_metrics_histogram where service_name = '$service_name' and metric_name = '$metric_histogram' group by attr;"
   }
  ]
 },
 "panels": [
  {
   "title": "(metric_gauge) $service_name $metric_gauge $metric_gauge_attributes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "__internal_schema",
     "rawSql": "select\r\n    $__time(timestamp),\r\n    value,\r\n    metric_unit\r\nfrom otel_metrics_gauge\r\nWHERE metric_name = '$metric_gauge'\r\nand service_name = '$service_name'\r\nand attributes = '$metric_gauge_attributes'\r\nand $__timeFilter(timestamp)\r\nORDER BY timestamp desc\r\nLIMIT 10000\r\n;"
    }
   ]
  },
  {
   "title": "[metric_sum] $service_name $metric_sum $metric_sum_attributes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "__internal_schema",
     "rawSql": "select\r\n    $__time(timestamp),\r\n    value,\r\n    metric_unit\r\nfrom otel_metrics_sum\r\nWHERE metric_name = '$metric_sum'\r\nand service_name = '$service_name'\r\nand attributes = '$metric_sum_attributes'\r\nand $__timeFilter(timestamp)\r\nORDER BY timestamp desc\r\nLIMIT 10000\r\n;"
    }
   ]
  },
  {
   "title": "[metric histogram] $service_name $metric_histogram $metric_histogram_attributes",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "__internal_schema",
     "rawSql": "select\r\n    $__time(timestamp),\r\n    concat('{', array_join(array_map((x, y) -> concat(json_quote(y), ':', x), bucket_counts, array_pushback(cast(explicit_bounds as array<string>), '+inf')), ','), '}') as buckets,\r\n    metric_unit\r\nfrom otel_metrics_histogram\r\nWHERE metric_name = '$metric_histogram'\r\nand service_name = '$service_name'\r\nand attributes = '$metric_histogram_attributes'\r\nand $__timeFilter(timestamp)\r\nORDER BY timestamp desc\r\nLIMIT 10000\r\n;"
    }
   ]
  }
 ]
}