{
 "title": "Traces",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "service_name",
    "query": "select distinct service_name from otel_traces;"
   },
   {
    "name": "operation",
    "label": "operation",
    "query": "select span_name from otel_traces where service_name = '$service_name' group by span_name;"
   },
   {
    "name": "status",
    "label": "status",
    "query": "error : STATUS_CODE_ERROR, ok : STATUS_CODE_OK, unset : STATUS_CODE_UNSET"
   },
   { "name": "trace_id", "label": "trace_id", "query": "0" }
  ]
 },
 "panels": [
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "__internal_schema",
     "rawSql": "with a as (\r\nselect trace_id, min(timestamp) as t\r\n  from otel_traces\r\n  where $__timeFilter(timestamp)\r\n    and service_name = '$service_name'\r\n    and ($operation = 'all' or span_name = $operation)\r\n    and ($status = 'all' or status_code = $status)\r\n  group by trace_id\r\n  order by t desc\r\n  limit 1000\r\n)\r\nselect\r\n    unix_timestamp(min(timestamp)) as time,\r\n    trace_id,\r\n    collect_set(service_name) as services,\r\n    count(*) as spans,\r\n    sum(if('STATUS_CODE_ERROR' = status_code, 1, 0)) as error_spans,\r\n    max(duration) / 1000 as 'duration (ms)'\r\nfrom otel_traces\r\nwhere trace_id in (select trace_id from a)\r\ngroup by trace_id\r\nORDER BY time desc\r\n;\r\n"
    }
   ]
  },
  {
   "title": "Trace",
   "type": "traces",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "__internal_schema",
     "rawSql": "select\r\n    trace_id as traceID,\r\n    span_id as spanID,\r\n    parent_span_id as parentSpanID,\r\n    span_name as operationName,\r\n    service_name as serviceName,\r\n    concat('[', array_join(array_map((x,y)->json_object(\"key\", x, \"value\", y),\r\n              map_keys(cast(cast(resource_attributes as text) as map<string, string>)),\r\n              map_values(cast(cast(resource_attributes as text) as map<string, string>))\r\n    ), ','), ']') as serviceTags,\r\n    unix_timestamp(timestamp) * 1000 as startTime,\r\n    duration / 1000 as duration,\r\n    concat('[', array_join(array_map((x,y)->json_object(\"key\", x, \"value\", y),\r\n              map_keys(cast(cast(span_attributes as text) as map<string, string>)),\r\n              map_values(cast(cast(span_attributes as text) as map<string, string>))\r\n    ), ','), ']') as tags,\r\n    span_kind as kind,\r\n    case status_code when 'STATUS_CODE_OK' then 1 when 'STATUS_CODE_ERROR' then 2 else 0 end as statusCode,\r\n    status_message as statusMessage,\r\n    scope_name as instrumentationLibraryName,\r\n    scope_version as instrumentationLibraryVersion,\r\n    trace_state as traceState\r\nfrom otel_traces\r\nwhere trace_id = '$trace_id'\r\n;"
    }
   ]
  },
  {
   "title": "Graph",
   "type": "nodeGraph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "dataset": "__internal_schema",
     "rawSql": "SELECT\r\n    cast(attributes['client'] as string) AS source,\r\n    cast(attributes['server'] as string) AS target,\r\n    max(if(attributes['failed'] = 0, value, null)) - min(if(attributes['failed'] = 0, value, null)) as detail__success_count,\r\n    max(if(attributes['failed'] = 1, value, null)) - min(if(attributes['failed'] = 1, value, null)) as detail__failed_count,\r\n    if(max(if(attributes['failed'] = 1, value, null)) - min(if(attributes['failed'] = 1, value, null)) > 0, 'red', 'green') as color\r\nFROM otel_metrics_sum\r\nWHERE metric_name = 'traces_service_graph_request_total'\r\n and $__timeFilter(timestamp) \r\nGROUP BY source, target\r\n;"
    }
   ]
  }
 ]
}